version = "1.0"
default_profile = "dev"
auto_migration = true
created_at = "2025-12-17T03:41:59.557739764Z"
updated_at = "2025-12-17T03:43:29.235945796Z"

[profiles.dev]
name = "dev"
created_at = "2025-12-17T03:42:11.446582145Z"
template = "development"
last_used = "2025-12-17T03:42:27.163745360Z"

[profiles.test]
name = "test"
created_at = "2025-12-17T03:43:29.235937951Z"
template = "development"

[profiles.prod]
name = "prod"
created_at = "2025-12-17T03:42:13.204353888Z"
template = "production"
last_used = "2025-12-17T03:42:40.571171624Z"
